# docker-compose.yml

version: '3.8'

services:
  # Define the Node.js app service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo:27017/your-database-name
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    command: ["npm", "run", "dev"]

  # Define the MongoDB service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
